{
    "extends": ["stylelint-config-standard"],
    "plugins": [
        "stylelint-order"
    ],
    "rules": {
        "at-rule-no-unknown": null,
        "at-rule-no-vendor-prefix": true,
        "color-hex-case": "lower",
        "color-hex-length": null,
        "color-named": "never",
        "comment-empty-line-before": "always",
        "comment-whitespace-inside": "always",
        "declaration-block-trailing-semicolon": "always",
        "declaration-colon-space-after": "always",
        "declaration-colon-space-before": "never",
        "declaration-no-important": true,
        "font-family-name-quotes": "always-unless-keyword",
        "indentation": 2,
        "media-feature-colon-space-after": "always",
        "media-feature-colon-space-before": "never",
        "media-feature-name-no-vendor-prefix": true,
        "media-feature-parentheses-space-inside": "never",
        "media-feature-range-operator-space-after": "always",
        "media-feature-range-operator-space-before": "always",
        'no-descending-specificity': null,
        "no-duplicate-selectors": true,
        "number-leading-zero": "never",
        "order/order": [
            "custom-properties",
            "declarations"
        ],
        "order/properties-alphabetical-order": true,
        "property-no-vendor-prefix": true,
        "rule-empty-line-before": "always",
        "selector-attribute-brackets-space-inside": "never",
        "selector-attribute-operator-space-after": "never",
        "selector-attribute-operator-space-before": "never",
        "selector-attribute-quotes": "always",
        "selector-combinator-space-after": "always",
        "selector-max-id": 0,
        "selector-max-type": 3,
        "selector-no-qualifying-type": null,
        "selector-no-vendor-prefix": true,
        "selector-pseudo-class-parentheses-space-inside": "never",
        "selector-pseudo-element-colon-notation": "double",
        "string-quotes": "single",
        "value-no-vendor-prefix": true
    }
}
