# Site settings
title: Diederik Dijkstra
email: diederikdijkstra@gmail.com
description: Front-end developer
baseurl: ""
url: "https://diederikdijkstra.nl"
enforce_ssl: diederikdijkstra.nl
future: true

#API
mapbox_token: pk.eyJ1IjoiZHlkcmljIiwiYSI6ImY1ZjIwNTAwNmYxYzVlMzJmZTdjZGE1MzJhMzIwMzZhIn0.PQCzoNuDuKyxEYpsfMUd-A
mapbox_style: mapbox://styles/dydric/cir6ftype0018cgm6a3hzzgpp

# Plugins
gems:
# - jemoji
# - jekyll-redirect-from
# - jekyll-sitemap
# - jekyll-feed

# Markdown
markdown: kramdown
# kramdown:
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   smart_quotes: lsquo,rsquo,ldquo,rdquo
#   enable_coderay: false

# Syntax
highlighter: rouge

# Exlucde
exclude:
- node_modules
- gulpfile.js
- package.json
- README.md
- Gemfile
- CNAME
- .editorconfig
- .scss-lint.yml
- src
