---
title: Diederik Dijkstra
timezone: Europe/Amsterdam
collections:
  albums:
    title: Albums
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: albums
  values:
    artist:
    cover_image:
    spotify:
    youtube:
email: diederikdijkstra@gmail.com
description: Front-end developer
baseurl:
url: https://diederikdijkstra.nl
enforce_ssl: diederikdijkstra.nl
future: true
gems:
- jemoji
markdown: kramdown
highlighter: rouge
exclude:
- ".editorconfig"
- ".eslintrc.yml"
- ".scss-lint.yml"
- CNAME
- config.js
- Gemfile
- gulpfile.js
- LICENSE
- modernizr.json
- node_modules
- npm-debug.log
- package.json
- README.md
