---
title: Diederik Dijkstra
timezone: Europe/Amsterdam
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  year:
    title: Year
    output: true
defaults:
- scope:
    path: ''
    type: year
  values:
    layout: year
    highlights:
    - description: 
    music:
      albums:
      - title: 
        artist: 
        cover_image: 
        spotify_url: 
      songs:
      - title: 
        artist: 
        spotify_url: 
    map:
      markers:
      - name: 
        latitude: 
        longitude: 
    strava:
      month:
      - distance: 
        rides: 
        time: 
    media:
      images:
      - 
      video:
      - 
email: diederikdijkstra@gmail.com
description: Front-end developer
baseurl: https://diederikdijkstra.nl
url: https://diederikdijkstra.nl
enforce_ssl: diederikdijkstra.nl
future: true
gems:
- jemoji
markdown: kramdown
highlighter: rouge
exclude:
- ".editorconfig"
- ".eslintrc.yml"
- ".scss-lint.yml"
- CNAME
- config.js
- Gemfile
- gulpfile.js
- LICENSE
- modernizr.json
- node_modules
- npm-debug.log
- package.json
- README.md
