---
title: Diederik Dijkstra
description: Front-end developer
keywords: Diederik, Diederik Dijkstra, Front-end developer, Leeuwarden

timezone: Europe/Amsterdam
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true

baseurl: https://diederikdijkstra.nl
url: https://diederikdijkstra.nl
enforce_ssl: diederikdijkstra.nl

GA: UA-382624-7
webfonts: "['Heebo:400,400i,700,700i', 'Source Code Pro:400,700', 'Anton']"

future: true
plugins:
  - jekyll-feed
markdown: kramdown
# highlighter: rouge

exclude:
- ".editorconfig"
- ".eslintrc.yml"
- ".scss-lint.yml"
- CNAME
- config.js
- Gemfile
- gulpfile.js
- LICENSE
- modernizr.json
- node_modules
- npm-debug.log
- package.json
- package-lock.json
- README.md
